### ISSUE TITLE
issue about data

### ISSUE THREAD

**Issue by 996237275** [xzluo97/MvMM-Demo#1]
The link you provided [https://zmiclab.github.io/projects/mscmrseg19/](url) was 404, file not found. 
Can you provide the available version. Any help will be highly appreciated.

**Comment by xzluo97** [comment]
Hi, the data can be found in this [link](https://zmiclab.github.io/zxh/0/mscmrseg19/).

**Comment by xzluo97** [comment]
You need to sign the [data registration form](https://zmiclab.github.io/zxh/0/mscmrseg19/file/ParticipantsAgreement.pdf) and send it to fudan_mscmr19@aliyun.com. The organizers will send back the correct data link.

**Comment by 996237275** [comment]
Well, thank you.
